### ISSUE TITLE
Getting error when attempting to run

### ISSUE THREAD

**Issue by Cryptonoodle** [nasa8x/node-genesis-block#1]
/root/genesis-block/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: this is not a typed array.
    at Function.from (native)
    at createInputScript (/root/genesis-block/genesis.js:61:64)
    at createTx (/root/genesis-block/genesis.js:72:17)
    at Object.handler (/root/genesis-block/genesis.js:40:37)
    at Object.runCommand (/root/genesis-block/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/root/genesis-block/node_modules/yargs/yargs.js:1042:24)
    at Object.Yargs.self.$0.self.resetOptions.self.reset.tmpOptions.local.forEach.Object.keys.reduce.arrayOptions.forEach.keys.forEach.key.forEach.Object.keys.forEach.Object.keys.forEach.self.config.self.demand.self.required.self.global.self.option.self.positional.self.group.self.exit.Object.defineProperty.get [as argv] (/root/genesis-block/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/genesis-block/genesis.js:55:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Any advice? Seems to be happening with all algos**

**Comment by nasa8x** [comment]
npm i yargs
