### ISSUE TITLE
something is wrog but...?

### ISSUE THREAD

**Issue by cryptosnail** [nasa8x/node-genesis-block#12]
npm install

> multi-hashing@1.0.3 install /home/cryptosnail/genesis-block/node_modules/multi-hashing
> node-gyp rebuild -masm=intel

make: Entering directory '/home/cryptosnail/genesis-block/node_modules/multi-hashing/build'
  CXX(target) Release/obj.target/multihashing/multihashing.o
../multihashing.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE lyra2rev2(Nan::NAN_METHOD_ARGS_TYPE)’:
../multihashing.cc:70:14: warning: unused variable ‘input_len’ [-Wunused-variable]
     uint32_t input_len = Buffer::Length(target);
              ^
../multihashing.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE lyra2z(Nan::NAN_METHOD_ARGS_TYPE)’:
../multihashing.cc:91:14: warning: unused variable ‘input_len’ [-Wunused-variable]
     uint32_t input_len = Buffer::Length(target);
              ^
../multihashing.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE boolberry(Nan::NAN_METHOD_ARGS_TYPE)’:
../multihashing.cc:172:40: warning: ‘v8::Local<v8::Uint32> v8::Value::ToUint32() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
             height = info[2]->ToUint32()->Uint32Value(); // TODO: This does not
                                        ^
In file included from /home/cryptosnail/.node-gyp/9.11.1/include/node/node.h:63:0,
                 from ../multihashing.cc:1:
/home/cryptosnail/.node-gyp/9.11.1/include/node/v8.h:9883:15: note: declared here
 Local<Uint32> Value::ToUint32() const {
               ^
  CC(target) Release/obj.target/multihashing/bcrypt.o
  CC(target) Release/obj.target/multihashing/blake.o
  CXX(target) Release/obj.target/multihashing/boolberry.o
In file included from ../crypto/cryptonote_core/cryptonote_format_utils.h:7:0,
                 from ../boolberry.cc:2:
../crypto/cryptonote_core/../wild_keccak.h: In function ‘int crypto::keccak_generic(const uint8_t*, size_t, uint8_t*, size_t)’:
../crypto/cryptonote_core/../wild_keccak.h:63:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                                       ^
../crypto/cryptonote_core/../wild_keccak.h: In function ‘int crypto::wild_keccak(const uint8_t*, size_t, uint8_t*, size_t, callback_t)’:
../crypto/cryptonote_core/../wild_keccak.h:98:39: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
     rsiz = sizeof(state_t_m) == mdlen ? HASH_DATA_AREA : 200 - 2 * mdlen;
                                       ^
../crypto/cryptonote_core/../wild_keccak.h: In instantiation of ‘int crypto::wild_keccak(const uint8_t*, size_t, uint8_t*, size_t, callback_t) [with f_traits = crypto::mul_f; callback_t = cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]::<lambda(uint64_t (&)[25], uint64_t (&)[24])>; uint8_t = unsigned char; size_t = long unsigned int]’:
../crypto/cryptonote_core/../wild_keccak.h:151:26:   required from ‘int crypto::wild_keccak_dbl(const uint8_t*, size_t, uint8_t*, size_t, callback_t) [with f_traits = crypto::mul_f; callback_t = cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]::<lambda(uint64_t (&)[25], uint64_t (&)[24])>; uint8_t = unsigned char; size_t = long unsigned int]’
../crypto/cryptonote_core/cryptonote_format_utils.h:15:43:   required from ‘bool cryptonote::get_blob_longhash_bb(const blobdata&, crypto::hash&, uint64_t, callback_t) [with callback_t = boolberry_hash(const char*, uint32_t, const char*, uint64_t, char*, uint64_t)::<lambda(uint64_t)>; blobdata = std::__cxx11::basic_string<char>; uint64_t = long unsigned int]’
../boolberry.cc:10:6:   required from here
cc1plus: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
  CC(target) Release/obj.target/multihashing/c11.o
  CC(target) Release/obj.target/multihashing/cryptonight.o
../cryptonight.c:60:13: warning: ‘mul’ defined but not used [-Wunused-function]
 static void mul(const uint8_t* a, const uint8_t* b, uint8_t* res) {
             ^
../cryptonight.c:74:13: warning: ‘sum_half_blocks’ defined but not used [-Wunused-function]
 static void sum_half_blocks(uint8_t* a, const uint8_t* b) {
             ^
../cryptonight.c:92:13: warning: ‘swap_blocks’ defined but not used [-Wunused-function]
 static void swap_blocks(uint8_t* a, uint8_t* b) {
             ^
  CC(target) Release/obj.target/multihashing/dcrypt.o
../dcrypt.c: In function ‘dcrypt_hash’:
../dcrypt.c:144:25: warning: pointer targets in passing argument 2 of ‘sha256’ differ in signedness [-Wpointer-sign]
     sha256(finalToHash, hash, len + lenMixedHash);
                         ^
../dcrypt.c:37:6: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 void sha256(unsigned char * instr, unsigned char * hash, unsigned int len)
      ^
  CC(target) Release/obj.target/multihashing/fresh.o
  CC(target) Release/obj.target/multihashing/fugue.o
  CC(target) Release/obj.target/multihashing/groestl.o
In file included from ../groestl.c:8:0:
../sha256.h:390:1: warning: ‘PBKDF2_SHA256’ defined but not used [-Wunused-function]
 PBKDF2_SHA256(const uint8_t * passwd, size_t passwdlen, const uint8_t * salt,
 ^
  CC(target) Release/obj.target/multihashing/hefty1.o
In file included from ../hefty1.c:7:0:
../sha256.h:390:1: warning: ‘PBKDF2_SHA256’ defined but not used [-Wunused-function]
 PBKDF2_SHA256(const uint8_t * passwd, size_t passwdlen, const uint8_t * salt,
 ^
  CC(target) Release/obj.target/multihashing/keccak.o
  CC(target) Release/obj.target/multihashing/lyra2.o
../lyra2.c:24:19: fatal error: Lyra2.h: No such file or directory
compilation terminated.
multihashing.target.mk:167: recipe for target 'Release/obj.target/multihashing/lyra2.o' failed
make: *** [Release/obj.target/multihashing/lyra2.o] Error 1
make: Leaving directory '/home/cryptosnail/genesis-block/node_modules/multi-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-38-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "-masm=intel"
gyp ERR! cwd /home/cryptosnail/genesis-block/node_modules/multi-hashing
gyp ERR! node -v v9.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@1.0.3 install: `node-gyp rebuild -masm=intel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cryptosnail/.npm/_logs/2018-04-06T02_00_33_341Z-debug.log

**Comment by nasa8x** [comment]
try `npm update`

**Comment by flyinghuman** [comment]
same here. 
```
> multi-hashing@1.0.3 install /home/user/dev/genesis-block/node_modules/multi-hashing
> node-gyp rebuild -masm=intel

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild" "-masm=intel"
gyp ERR! cwd /home/user/dev/genesis-block/node_modules/multi-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 4.13.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.3 install: `node-gyp rebuild -masm=intel`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multi-hashing@1.0.3 install script 'node-gyp rebuild -masm=intel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild -masm=intel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/dev/genesis-block/npm-debug.log
```
