### ISSUE TITLE
Cannot get the script to work

### ISSUE THREAD

**Issue by swatchie-1** [nasa8x/node-genesis-block#17]
Hi Nasa, thanks for your wonderful script. Can you help to get the script to work? I keep getting erros: 

root@orien-2:~/genesis-maker/genesis-block/genesis-block/genesis-block# node genesis -a quark
/root/genesis-maker/genesis-block/genesis-block/genesis-block/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: this is not a typed array.
    at Function.from (native)
    at createInputScript (/root/genesis-maker/genesis-block/genesis-block/genesis-block/genesis.js:61:64)
    at createTx (/root/genesis-maker/genesis-block/genesis-block/genesis-block/genesis.js:72:17)
    at Object.handler (/root/genesis-maker/genesis-block/genesis-block/genesis-block/genesis.js:40:37)
    at Object.runCommand (/root/genesis-maker/genesis-block/genesis-block/genesis-block/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/root/genesis-maker/genesis-block/genesis-block/genesis-block/node_modules/yargs/yargs.js:1042:24)
    at Object.Yargs.self.$0.self.resetOptions.self.reset.tmpOptions.local.forEach.Object.keys.reduce.arrayOptions.forEach.keys.forEach.key.forEach.Object.keys.forEach.Object.keys.forEach.self.config.self.demand.self.required.self.global.self.option.self.positional.self.group.self.exit.Object.defineProperty.get [as argv] (/root/genesis-maker/genesis-block/genesis-block/genesis-block/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/genesis-maker/genesis-block/genesis-block/genesis-block/genesis.js:55:5)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)

**Comment by FndNur1Labs** [comment]
same here...lol wth to fixed this?

**Comment by cryptforall** [comment]
download the qurak hash

**Comment by ChrisElCrebel** [comment]
Please fix this Sir!

/home/crebell/node-genesis-block/node_modules/yargs/yargs.js:1133
      else throw err
           ^

**Comment by cryptforall** [comment]
npm i yargs
