### ISSUE TITLE
Cannot generate for neoscrypt

### ISSUE THREAD

**Issue by ArenaCoinDev** [nasa8x/node-genesis-block#18]
Not sure what i am doing wrong but it wont work when generating a genesis block

**Comment by ArenaCoinDev** [comment]
root@mmocdev-VirtualBox:~/Desktop/TEST1/genesis-block# node genesis -a neoscrypt -z "arena coin starts now!"
module.js:328
    throw err;
    ^

Error: Cannot find module 'multi-hashing'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/Desktop/TEST1/genesis-block/genesis.js:4:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)

**Comment by nasa8x** [comment]
First, run install package.

> npm install

**Comment by nasa8x** [comment]
node genesis -a neoscrypt -z "arena coin starts now"
---------------
algorithm: neoscrypt
pzTimestamp: arena coin starts now
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
bits: 504365040
time: 1532829728
merkle root hash: b453206220cd8bcd0ae16f77868c248cfae6e27a9eda0f9fededb21fb5c588a1
Searching for genesis hash...
nonce: 14767
genesis hash: 00000e1ced5f4e2f71e84b4be715f140da060014d5e799a44ad88c492784cd10

**Comment by ArenaCoinDev** [comment]
i ran the npm install but what am i missing, how did you get it to return this info

**Comment by nasa8x** [comment]
Run with node.js version 8.x.x
git clone https://github.com/nasa8x/node-genesis-block.git genesis-block
cd genesis-block
npm install

**Comment by ArenaCoinDev** [comment]
yup did this, and got the warning that the version was not current, which i ignored. was it the node genesis line?

**Comment by nasa8x** [comment]
```node genesis -a neoscrypt -z "arena coin starts now"```

**Comment by ArenaCoinDev** [comment]
am i supposed to do this within the master folder or outside of it

**Comment by ArenaCoinDev** [comment]
when i try to install within the master folder (arena-master) i get this error

root@mmocdev-VirtualBox:~/Desktop/TEST1/arena-master/genesis-block# npm install
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2

> multi-hashing@1.0.3 install /root/Desktop/TEST1/arena-master/genesis-block/node_modules/multi-hashing
> node-gyp rebuild -masm=intel

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/root/Desktop/TEST1/arena-master/genesis-block/node_modules/multi-hashing/build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild" "-masm=intel"
gyp ERR! cwd /root/Desktop/TEST1/arena-master/genesis-block/node_modules/multi-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
genesis-block@1.0.0 /root/Desktop/TEST1/arena-master/genesis-block
├── crypto@1.0.1 
└─┬ yargs@11.1.0 
  ├─┬ cliui@4.1.0 
  │ ├─┬ strip-ansi@4.0.0 
  │ │ └── ansi-regex@3.0.0 
  │ └─┬ wrap-ansi@2.1.0 
  │   ├─┬ string-width@1.0.2 
  │   │ ├── code-point-at@1.1.0 
  │   │ └─┬ is-fullwidth-code-point@1.0.0 
  │   │   └── number-is-nan@1.0.1 
  │   └─┬ strip-ansi@3.0.1 
  │     └── ansi-regex@2.1.1 
  ├── decamelize@1.2.0 
  ├─┬ find-up@2.1.0 
  │ └─┬ locate-path@2.0.0 
  │   ├─┬ p-locate@2.0.0 
  │   │ └─┬ p-limit@1.3.0 
  │   │   └── p-try@1.0.0 
  │   └── path-exists@3.0.0 
  ├── get-caller-file@1.0.3 
  ├─┬ os-locale@2.1.0 
  │ ├─┬ execa@0.7.0 
  │ │ ├─┬ cross-spawn@5.1.0 
  │ │ │ ├─┬ lru-cache@4.1.3 
  │ │ │ │ ├── pseudomap@1.0.2 
  │ │ │ │ └── yallist@2.1.2 
  │ │ │ ├─┬ shebang-command@1.2.0 
  │ │ │ │ └── shebang-regex@1.0.0 
  │ │ │ └─┬ which@1.3.1 
  │ │ │   └── isexe@2.0.0 
  │ │ ├── get-stream@3.0.0 
  │ │ ├── is-stream@1.1.0 
  │ │ ├─┬ npm-run-path@2.0.2 
  │ │ │ └── path-key@2.0.1 
  │ │ ├── p-finally@1.0.0 
  │ │ ├── signal-exit@3.0.2 
  │ │ └── strip-eof@1.0.0 
  │ ├─┬ lcid@1.0.0 
  │ │ └── invert-kv@1.0.0 
  │ └─┬ mem@1.1.0 
  │   └── mimic-fn@1.2.0 
  ├── require-directory@2.1.1 
  ├── require-main-filename@1.0.1 
  ├── set-blocking@2.0.0 
  ├─┬ string-width@2.1.1 
  │ └── is-fullwidth-code-point@2.0.0 
  ├── which-module@2.0.0 
  ├── y18n@3.2.1 
  └─┬ yargs-parser@9.0.2 
    └── camelcase@4.1.0 

npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.3 install: `node-gyp rebuild -masm=intel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@1.0.3 install script 'node-gyp rebuild -masm=intel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild -masm=intel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Desktop/TEST1/arena-master/genesis-block/npm-debug.log
root@mmocdev-VirtualBox:~/Desktop/TEST1/arena-master/genesis-block#

**Comment by nasa8x** [comment]
npm install -g node-gyp

**Comment by ArenaCoinDev** [comment]
installed and now when i run npm install i get this error


root@mmocdev-VirtualBox:~/Desktop/TEST1/genesis-block# npm install
npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2

> multi-hashing@1.0.3 install /root/Desktop/TEST1/genesis-block/node_modules/multi-hashing
> node-gyp rebuild -masm=intel

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/root/Desktop/TEST1/genesis-block/node_modules/multi-hashing/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, stat '/root/Desktop/TEST1/genesis-block/node_modules/multi-hashing/.node-gyp/4.2.6'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/bin/node-gyp" "rebuild" "-masm=intel"
gyp ERR! cwd /root/Desktop/TEST1/genesis-block/node_modules/multi-hashing
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! multi-hashing@1.0.3 install: `node-gyp rebuild -masm=intel`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@1.0.3 install script 'node-gyp rebuild -masm=intel'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild -masm=intel
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multi-hashing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/Desktop/TEST1/genesis-block/npm-debug.log
root@mmocdev-VirtualBox:~/Desktop/TEST1/genesis-block#

**Comment by nasa8x** [comment]
Your node.js v4.2.6 upgrade to 8.x.x

**Comment by ArenaCoinDev** [comment]
upgraded, and now running , i returned this 

algorithm: neoscrypt
pzTimestamp: Arena starts now, let the battle begin!
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
bits: 504365040
time: 1532845874
merkle root hash: aa6af392c6b364c8585f5ca2385310bdc08b0d805f3ff4cb0fb1b13cbbf4109c
Searching for genesis hash...
nonce: 1881937
genesis hash: 00000b8ce1f8a903f5d592629973f1274a97d3c14fd1f97ebf87199b53773abb


now when applied to my source it gives the aborted error and core dumped message. Does this program have to run in a certain dir to get the proper info? and where is that

**Comment by nasa8x** [comment]
Refer to this documentation, then change the params information. Goodluck!
https://cdn.discordapp.com/attachments/418988612911366145/423869420730056704/Cloning-Bitcoin-0.8.99.pdf

**Comment by ArenaCoinDev** [comment]
so it is just a matter of where i have input the returned data not that the returned data is incorrect. I just wanted to confirm this

 chainparams.cpp:118: CMainParams::CMainParams(): Assertion `consensus.hashGenesisBlock == uint256S("00000b8ce1f8a903f5d592629973f1274a97d3c14fd1f97ebf87199b53773abb")' failed.
Aborted (core dumped)

**Comment by ArenaCoinDev** [comment]
Will do, Thank you for your help, Ill report back when i get things running. Thank you again

**Comment by ArenaCoinDev** [comment]
why do the nBits in the source code come up like 0x1e0ffff0 but when i generate a genesis block with your program my nBits are 504365040 do i add the 0x in front of it?

**Comment by ArenaCoinDev** [comment]
ok,  i have everything solved for the main network, how do i avoid this testnet issue? i cannot seem to find the debug file (cd ~/.arena) to enter the generated testnet values

arenad: chainparams.cpp:217: CTestNetParams::CTestNetParams(): Assertion `consensus.hashGenesisBlock == uint256S("000003e6bdc6aac8d8a8f919b84c09d56b67be1164df10d3b3f28fdd8ffd6f64")' failed.
Aborted (core dumped)
