### ISSUE TITLE
i have got this error when run genesis 

### ISSUE THREAD

**Issue by devAji917** [nasa8x/node-genesis-block#2]
root@vmi167433:~/genesis-block-node# node genesis -a quark
/root/genesis-block-node/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: this is not a typed array.
    at Function.from (native)
    at createInputScript (/root/genesis-block-node/genesis.js:61:64)
    at createTx (/root/genesis-block-node/genesis.js:72:17)
    at Object.handler (/root/genesis-block-node/genesis.js:40:37)
    at Object.runCommand (/root/genesis-block-node/node_modules/yargs/lib/comman                                                                                                                                                             d.js:235:44)
    at Object.parseArgs [as _parseArgs] (/root/genesis-block-node/node_modules/y                                                                                                                                                             args/yargs.js:1042:24)
    at Object.Yargs.self.$0.self.resetOptions.self.reset.tmpOptions.local.forEac                                                                                                                                                             h.Object.keys.reduce.arrayOptions.forEach.keys.forEach.key.forEach.Object.keys.f                                                                                                                                                             orEach.Object.keys.forEach.self.config.self.demand.self.required.self.global.sel                                                                                                                                                             f.option.self.positional.self.group.self.exit.Object.defineProperty.get [as argv                                                                                                                                                             ] (/root/genesis-block-node/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/genesis-block-node/genesis.js:55:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Please help me and hope reply to me. what is the reason of this error?

**Comment by nasa8x** [comment]
Are sure install yargs: `npm i yargs`

**Comment by devAji917** [comment]
i have installed yargs as you said. npm i yargs
but still same error.
help me please

**Comment by alphanode** [comment]
can someone tell me what he/she has done to solve it? have the same error and YES yargs is installed
