### ISSUE TITLE
scrypt

### ISSUE THREAD

**Issue by grantmundl** [nasa8x/node-genesis-block#26]
not working with scrypt, get this error
/home/ubuntu/node-genesis-block/node_modules/yargs/yargs.js:1109
      else throw err
           ^

Error: You must provide buffer to hash, N value, and R value
    at PoW (/home/ubuntu/node-genesis-block/genesis.js:158:59)
    at Object.require.alias.alias.alias.alias.alias.alias.alias.alias.alias.help.command [as handler] (/home/ubuntu/node-genesis-block/genesis.js:51:9)
    at Object.runCommand (/home/ubuntu/node-genesis-block/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/ubuntu/node-genesis-block/node_modules/yargs/yargs.js:1050:24)
    at Object.get [as argv] (/home/ubuntu/node-genesis-block/node_modules/yargs/yargs.js:965:21)
    at Object.<anonymous> (/home/ubuntu/node-genesis-block/genesis.js:57:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
working with other algos

**Comment by RecoX** [comment]
same issue here.

**Comment by xsa-dev** [comment]
You need to send N value, and R value to multihashing.node ...

**Comment by vuicash** [comment]
node genesis -a scrypt
Error for me to
Error: You must provide buffer to hash, N value, and R value

**Comment by xsa-dev** [comment]
I am use this script for generating genesis block for scrypt: https://github.com/lhartikk/GenesisH0

But this worked only for old old python 2.7 only, need support for python 3.8+

**Comment by anonymousess** [comment]
For old version
Ubuntu 18.
```
apt install python
apt install python-pip
```
Worked for me

> I am use this script for generating genesis block for scrypt: https://github.com/lhartikk/GenesisH0
> 
> But this worked only for old old python 2.7 only, need support for python 3.8+
