### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by devAji917** [nasa8x/node-genesis-block#6]
i am going to run genesis using node-genesis-block.
but when i run "node genesis -a quark", error happens.
the errors are as follows.
root@vmi167433:~/genesis-block-node# node genesis -a quark
/root/genesis-block-node/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: this is not a typed array.
    at Function.from (native)
    at createInputScript (/root/genesis-block-node/genesis.js:61:64)
    at createTx (/root/genesis-block-node/genesis.js:72:17)
    at Object.handler (/root/genesis-block-node/genesis.js:40:37)
    at Object.runCommand (/root/genesis-block-node/node_modules/yargs/lib/comman                                                                                                                                                             d.js:235:44)
    at Object.parseArgs [as _parseArgs] (/root/genesis-block-node/node_modules/y                                                                                                                                                             args/yargs.js:1042:24)
    at Object.Yargs.self.$0.self.resetOptions.self.reset.tmpOptions.local.forEac                                                                                                                                                             h.Object.keys.reduce.arrayOptions.forEach.keys.forEach.key.forEach.Object.keys.f                                                                                                                                                             orEach.Object.keys.forEach.self.config.self.demand.self.required.self.global.sel                                                                                                                                                             f.option.self.positional.self.group.self.exit.Object.defineProperty.get [as argv                                                                                                                                                             ] (/root/genesis-block-node/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/genesis-block-node/genesis.js:55:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
root@vmi167433:~/genesis-block-node# npm i yargs
root@vmi167433:~/genesis-block-node#  node genesis -a quark
/root/genesis-block-node/node_modules/yargs/yargs.js:1101
      else throw err
           ^

TypeError: this is not a typed array.
    at Function.from (native)
    at createInputScript (/root/genesis-block-node/genesis.js:61:64)
    at createTx (/root/genesis-block-node/genesis.js:72:17)
    at Object.handler (/root/genesis-block-node/genesis.js:40:37)
    at Object.runCommand (/root/genesis-block-node/node_modules/yargs/lib/comman                                                                                                                                                             d.js:235:44)
    at Object.parseArgs [as _parseArgs] (/root/genesis-block-node/node_modules/y                                                                                                                                                             args/yargs.js:1042:24)
    at Object.Yargs.self.$0.self.resetOptions.self.reset.tmpOptions.local.forEac                                                                                                                                                             h.Object.keys.reduce.arrayOptions.forEach.keys.forEach.key.forEach.Object.keys.f                                                                                                                                                             orEach.Object.keys.forEach.self.config.self.demand.self.required.self.global.sel                                                                                                                                                             f.option.self.positional.self.group.self.exit.Object.defineProperty.get [as argv                                                                                                                                                             ] (/root/genesis-block-node/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/root/genesis-block-node/genesis.js:55:5)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

i have installed yargs. npm i yargs as nasa8x said. but still same error.
i hope to help me plz!!!

**Comment by alphanode** [comment]
same here!

**Comment by nasa8x** [comment]
What's your Node version? Recommend Node v8.x

**Comment by nasa8x** [comment]
It's ok: http://prntscr.com/ixliee

**Comment by devAji917** [comment]
thanks
