### ISSUE TITLE
Scrypt generate

### ISSUE THREAD

**Issue by mafalatexb** [nasa8x/node-genesis-block#8]
How does one specify the N and R value?

```
x@x-virtual-machine:~/Desktop/crypto/genesis-block$ node genesis.js -a scrypt
---------------
algorithm: scrypt
pzTimestamp: Don't work for weekends, work for our goals.
pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
bits: 504365040
time: 1522705710
merkle root hash: f5239467dd2a9dd0fce7a3babc03c7985eab2229c62e3d5670375f305753c9cc
Searching for genesis hash...
/home/x/Desktop/crypto/genesis-block/node_modules/yargs/yargs.js:1101
      else throw err
           ^

Error: You must provide buffer to hash, N value, and R value
    at PoW (/home/x/Desktop/crypto/genesis-block/genesis.js:143:59)
    at Object.require.alias.alias.alias.alias.alias.alias.alias.alias.alias.help.command [as handler] (/home/x/Desktop/crypto/genesis-block/genesis.js:50:9)
    at Object.runCommand (/home/x/Desktop/crypto/genesis-block/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/x/Desktop/crypto/genesis-block/node_modules/yargs/yargs.js:1042:24)
    at Object.get [as argv] (/home/x/Desktop/crypto/genesis-block/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/x/Desktop/crypto/genesis-block/genesis.js:55:5)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
```

**Comment by WolfClover** [comment]
same problem

**Comment by hashcrack256** [comment]
Needs a minor change to the code, please see https://github.com/hashcrack256/node-genesis-block which has N = 1024 and R = 1 hardcoded in to match Litecoin's scrypt PoW parameters.

**Comment by gill6151** [comment]
> Needs a minor change to the code, please see https://github.com/hashcrack256/node-genesis-block which has N = 1024 and R = 1 hardcoded in to match Litecoin's scrypt PoW parameters.

this fork has the exact same issue, no buffer, N or R value provided
